apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-management-ms
  template:
    metadata:
      labels:
        app: user-management-ms
    spec:
      containers:
        - name: user-management-ms
          image: 891377328281.dkr.ecr.us-east-1.amazonaws.com/user_management_ms:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-management-ms
spec:
  selector:
    app: user-management-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer